# Copyright 2025 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-assist
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: tekton-assist
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: tekton-assist
    pruner.tekton.dev/release: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-assist
      app.kubernetes.io/name: tekton-assist
      app.kubernetes.io/component: tekton-assist
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-assist
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
      labels:
        app: tekton-assist
        app.kubernetes.io/name: tekton-assist
        app.kubernetes.io/component: tekton-assist
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "devel"
        app.kubernetes.io/part-of: tekton-assist
        version: "devel"
        assist.tekton.dev/release: "devel"
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: tekton-assist
                    app.kubernetes.io/name: tekton-assist
                    app.kubernetes.io/component: tekton-assist
                    app.kubernetes.io/instance: default
                    app.kubernetes.io/part-of: tekton-assist
                topologyKey: kubernetes.io/hostname
              weight: 100
      serviceAccountName: tekton-assist
      containers:
        - name: diagnose
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://github.com/redhat-community-ai-tools/tekton-assist/cmd/diagnose
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - name: metrics
              containerPort: 9090
          envFrom:
            - configMapRef: 
                name: tekton-assist-config
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: api-key
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
            # User 65532 is the distroless nonroot user ID
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tekton-assist
    app.kubernetes.io/component: tekton-assist
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: tekton-assist
    pruner.tekton.dev/release: "devel"
    app: tekton-assist
    version: "devel"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
  name: tekton-assist
  namespace: openshift-pipelines
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      targetPort: 9090
      port: 9090
  selector:
    app.kubernetes.io/name: tekton-assist
    app.kubernetes.io/component: tekton-assist
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-assist
